Challange GITHUB_TOKEN token before using it (#30)
* finish action

* improve

* test

* improve error handling

* mute jq warn

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -12,7 +12,7 @@ inputs:
   token:
     description: "Token to access GitHub API"
     required: false
-    default: "${{ github.token }}"
+    default: ""
   force:
     description: "Skip cache and force reinstallation"
     required: false
@@ -20,6 +20,37 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: "Choose token header"
+      id: choose_token
+      shell: bash
+      run: |
+        if [[ -n "${{ inputs.token }}" ]]; then
+          echo "Using provided token"
+          echo "flag=-H \"Authorization: Bearer ${{ inputs.token }}\" >> $GITHUB_OUTPUT"
+          exit 0
+        else
+          echo "No token provided"
+        fi
+
+        if [[ -n "${{ github.token }}" ]]; then
+          echo "Challanging GITHUB_TOKEN"
+          curl_output="$(curl -L -s \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ github.token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/)"
+          
+          if [[ "$(echo "$curl_output" | jq -r '.message')" == "Bad credentials" ]]; then
+            echo "GITHUB_TOKEN is invalid"
+          else
+            echo "GITHUB_TOKEN is valid"
+            echo "flag=-H \"Authorization: Bearer ${{ github.token }}\" >> $GITHUB_OUTPUT"
+            exit 0
+          fi
+        fi
+
+        echo "No valid token provided, proceeding without authentication. Note that this may cause issues with API rate limits."
+
     - name: "Calculate cache key"
       id: calculate
       shell: bash
@@ -27,9 +58,29 @@ runs:
         KYMA_CLI_VERSION="${{ inputs.version }}"
 
         if [[ -z "${KYMA_CLI_VERSION}" || "${KYMA_CLI_VERSION}" == "latest" ]]; then
-          KYMA_CLI_VERSION="$(gh release list --repo kyma-project/cli --json name,isLatest --jq '.[] | select(.isLatest)|.name')"
+          CURL_OUTPUT="$(curl -L -s \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/kyma-project/cli/releases)"
+          
+          if [[ "$( echo $CURL_OUTPUT | jq .message 2>/dev/null)" != "" ]]; then
+            echo "Error fetching releases: $(echo $CURL_OUTPUT | jq -r .message)"
+            exit 1
+          else
+            KYMA_CLI_VERSION="$(echo $CURL_OUTPUT | jq -r '[.[] | select(.name != "0.0.0-dev")][0].name')"
+          fi
         elif [[ "${KYMA_CLI_VERSION}" == "stable" ]]; then
-          KYMA_CLI_VERSION="$(gh release list --repo kyma-project/cli --json name,isLatest --jq '.[] | select(.isLatest)|select(.isPrerelease|not)|.name')"
+          CURL_OUTPUT="$(curl -L -s \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            ${{ steps.choose_token.outputs.flag }} \
+            https://api.github.com/repos/kyma-project/cli/releases/latest)"
+          if [[ "$( echo $CURL_OUTPUT | jq .message 2>/dev/null)" != "" ]]; then
+            echo "Error fetching latest release: $(echo $CURL_OUTPUT | jq -r .message)"
+            exit 1
+          else
+            KYMA_CLI_VERSION="$(echo $CURL_OUTPUT | jq -r '.name')"
+          fi
         elif [[ "${KYMA_CLI_VERSION}" == "nightly" ]]; then
           KYMA_CLI_VERSION="0.0.0-dev"
         fi
@@ -62,7 +113,6 @@ runs:
           echo "kyma_cli_path=${target}/kyma" >> $GITHUB_OUTPUT
         fi
       env:
-        GITHUB_TOKEN: ${{ inputs.token }}
         TARGET_DIR: ${{ inputs.target-dir }}
     - name: Kyma CLI cache"
       id: cache
@@ -96,7 +146,18 @@ runs:
 
         CLI_TMPDIR=cli-$(date "+%Y-%m-%d_%H_%M_%S")
         mkdir -p "${CLI_TMPDIR}"
-        gh release download --repo kyma-project/cli "${KYMA_CLI_VERSION}" -p "${filename}" -O "${CLI_TMPDIR}/cli.${EXT}"
+        DOWNLOAD_HTTP_CODE=$(curl -L -s \
+          -H "Accept: application/vnd.github+json" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          ${{ steps.choose_token.outputs.flag }} \
+          "https://github.com/kyma-project/cli/releases/download/${KYMA_CLI_VERSION}/${filename}" \
+          -o "${CLI_TMPDIR}/cli.${EXT}" -w "%{http_code}")
+
+        if [[ "${DOWNLOAD_HTTP_CODE}" -ne 200 ]]; then
+          echo "Failed to download Kyma CLI. HTTP status code: ${DOWNLOAD_HTTP_CODE}"
+          rm -rf "${CLI_TMPDIR}"
+          exit 1
+        fi
 
         if [[ "${OS}" == "Windows" ]]; then
           unzip "${CLI_TMPDIR}/cli.zip" -d "${CLI_TMPDIR}"
@@ -118,7 +179,6 @@ runs:
         rm -r "${CLI_TMPDIR}"
         echo "Installed $(${TARGET_PATH} version) to $(readlink -f "${TARGET_PATH}")"
       env:
-        GITHUB_TOKEN: ${{ inputs.token }}
         KYMA_CLI_VERSION: ${{ steps.calculate.outputs.kyma_cli_version }}
         TARGET_PATH: ${{ steps.calculate.outputs.kyma_cli_path }}
         ARCH: ${{ steps.calculate.outputs.kyma_cli_arch }}
